dbt_orchestration:
  outputs:
    dev:
      dataset: <your GCP dataset>
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: <your-gcp-credentials-path>
      location: US
      method: service-account
      priority: interactive
      project: <your-gcp-project-id>
      threads: 1
      type: bigquery
  target: dev